- hosts: tag_Name_tf_instance_devops
  serial: 1
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: get info on back container
      docker_container_info:
        name: lahaus
      register: result
      vars:
        ansible_python_interpreter: /bin/python3.8

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: lahaus
        state: stopped
      when: result.exists
      vars:
        ansible_python_interpreter: /bin/python3.8
    
    - name: remove container
      docker_container:
        name: lahaus
        state: absent
      when: result.exists
      vars:
        ansible_python_interpreter: /bin/python3.8
    
    - name: remove image
      docker_image:
        state: absent
        name: alejandraramos/lahaus
      vars:
        ansible_python_interpreter: /bin/python3.8

    - name: Execute docker container
      docker_container:
        name: lahaus
        image: alejandraramos/lahaus
        pull: true
        state: started
        published_ports:
          - "5000:5000"
        env:
          APP_SETTINGS: 'config.DevelopmentConfig'
          DATABASE_URL: '{{ database_url }}'
      register: my_service_status
      vars:
        ansible_python_interpreter: /bin/python3.8