node {
  step([$class: 'WsCleanup'])


  stage('Checkout aditional repo') {
    dir('ConfigManager') {
      git branch: 'master', url: "https://github.com/alejandraRamos/lahaus-project.git"
    }
  }

  stage('Execute deployment with ansible') {
    dir('ConfigManager') {
      sh """
        sudo ansible-playbook -i Inventory/aws_ec2.yaml \
        -l tag_Name_tf-instance-devops \
        ini.yml \
        --private-key="${env.pemPath}" \
        -u ubuntu -vvv \
        -e tag=${params.TAG} \
        -e back_host=localhost
      """
    }
  }

}