node {
  step([$class: 'WsCleanup'])


  stage('Checkout SCM') {
        checkout csm
  }

  stage('Execute deployment with ansible') {
    dir('ConfigManager') {
      sh """
        sudo ansible-playbook -i Inventory/aws_ec2.yaml \
        -l tag_Name_tf-instance-devops \
        ini.yml \
        --private-key="${env.pemPath}" \
        -u ec2-user -vvv \
        -e tag=${params.TAG} \
        -e back_host=localhost
      """
    }
  }

}