node {
  step([$class: 'WsCleanup'])


  stage('Checkout SCM') {
        checkout scm
  }

  stage('Execute deployment with ansible') {
    dir('ConfigManager') {
      sh """
        sudo ansible-playbook -i Inventory/aws_ec2.yaml \
        -l tag_Name_tf_instance_devops \
        ini.yml \
        --private-key="${env.pemPath}" \
        -u ubuntu -vvv \
        -e tag=${params.TAG} \
        -e database_url=postgresql://myuser:password@${env.ip_db}/lahaus
      """
    }
  }

}